time="2024-08-07T17:13:51+09:00" level=warning msg="/home/yoonchcul/Documents/Hanium_2024/AEYE_AI/develop/Docker/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
time="2024-08-07T17:13:51+09:00" level=warning msg="Found orphan containers ([seminar_container]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
 Container opticnet_container  Running
 Container network_operator_container  Created
Attaching to network_operator_container, opticnet_container
network_operator_container  | Watching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 07, 2024 - 08:13:51
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:13:56 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:13:56 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:13:56 [ NetOper API ANO ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mMW - Inference received message : Request AI Inference [39m
network_operator_container  | -----------------------------------------
network_operator_container  | Internal Server Error: /mw/ai-inference/
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
network_operator_container  |     response = get_response(request)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
network_operator_container  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
network_operator_container  |     return view_func(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
network_operator_container  |     return self.dispatch(request, *args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 511, in dispatch
network_operator_container  |     self.response = self.finalize_response(request, response, *args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 423, in finalize_response
network_operator_container  |     assert isinstance(response, HttpResponseBase), (
network_operator_container  | AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
network_operator_container  | [07/Aug/2024 08:13:56] [35;1m"POST /mw/ai-inference/ HTTP/1.1" 500 70944[0m
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:13:56 [ NetOper API ANO ] send to : [34m[ NetOper API - ANO ][39m
network_operator_container  | [31m[error] [31mfailed to send data to : http://127.0.0.1:3000/mw/ai-inference/
network_operator_container  |         received message from the server: Failed to Receive Data [NetOper - ANO][39m
network_operator_container  | -----------------------------------------
network_operator_container  | Bad Request: /api/ai-network-operator/
network_operator_container  | [07/Aug/2024 08:13:56] [31;1m"POST /api/ai-network-operator/ HTTP/1.1" 400 76[0m
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 07, 2024 - 08:14:53
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:14:57 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:14:57 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:14:57 [ NetOper API ANO ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mMW - Inference received message : Request AI Inference [39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:14:57 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received data from : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------[07/Aug/2024 08:14:57] [m"POST /mw/ai-inference/ HTTP/1.1" 200 6[0m
network_operator_container  | 
network_operator_container  | Internal Server Error: /api/ai-network-operator/
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
network_operator_container  |     response = get_response(request)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
network_operator_container  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
network_operator_container  |     return view_func(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
network_operator_container  |     return self.dispatch(request, *args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
network_operator_container  |     response = self.handle_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
network_operator_container  |     self.raise_uncaught_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
network_operator_container  |     raise exc
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
network_operator_container  |     response = handler(request, *args, **kwargs)
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 47, in create
network_operator_container  |     response = aeye_ai_inference_request(image, url)
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 87, in aeye_ai_inference_request
network_operator_container  |     whoami, message = aeye_get_data_from_response(response)
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 96, in aeye_get_data_from_response
network_operator_container  |     whoami = response_data.get('whoami', '')
network_operator_container  | AttributeError: 'str' object has no attribute 'get'
network_operator_container  | [07/Aug/2024 08:14:57] [35;1m"POST /api/ai-network-operator/ HTTP/1.1" 500 99080[0m
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 07, 2024 - 08:15:38
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:15:40 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:15:40 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:15:40 [ NetOper API ANO ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mMW - Inference received message : Request AI Inference [39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:15:40 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received data from : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------[07/Aug/2024 08:15:40] [m"POST /mw/ai-inference/ HTTP/1.1" 200 34[0m
network_operator_container  | 
network_operator_container  | [07/Aug/2024 08:15:40] [m"POST /api/ai-network-operator/ HTTP/1.1" 200 46[0m
network_operator_container  | /app/AEYE_Network_Operator/settings.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | Exception in thread django-main-thread:
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
network_operator_container  |     self.run()
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
network_operator_container  |     self._target(*self._args, **self._kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
network_operator_container  |     fn(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
network_operator_container  |     self.check(display_num_errors=True)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 469, in check
network_operator_container  |     raise SystemCheckError(msg)
network_operator_container  | django.core.management.base.SystemCheckError: [31;1mSystemCheckError: System check identified some issues:
network_operator_container  | [0m
network_operator_container  | ERRORS:
network_operator_container  | [31;1m?: (urls.E006) The MEDIA_URL setting must end with a slash.[0m
network_operator_container  | 
network_operator_container  | System check identified 1 issue (0 silenced).
network_operator_container  | /app/AEYE_Network_Operator/settings.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | Exception in thread django-main-thread:
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
network_operator_container  |     self.run()
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
network_operator_container  |     self._target(*self._args, **self._kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
network_operator_container  |     fn(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
network_operator_container  |     self.check(display_num_errors=True)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 469, in check
network_operator_container  |     raise SystemCheckError(msg)
network_operator_container  | django.core.management.base.SystemCheckError: [31;1mSystemCheckError: System check identified some issues:
network_operator_container  | [0m
network_operator_container  | ERRORS:
network_operator_container  | [31;1m?: (urls.E006) The MEDIA_URL setting must end with a slash.[0m
network_operator_container  | 
network_operator_container  | System check identified 1 issue (0 silenced).
network_operator_container  | /app/AEYE_Network_Operator/settings.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 07, 2024 - 08:16:25
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:16:27 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:16:27 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:16:27 [ NetOper API ANO ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mMW - Inference received message : Request AI Inference [39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:16:27 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received data from : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------[07/Aug/2024 08:16:27] [m"POST /mw/ai-inference/ HTTP/1.1" 200 34[0m
network_operator_container  | 
network_operator_container  | [07/Aug/2024 08:16:27] [m"POST /api/ai-network-operator/ HTTP/1.1" 200 46[0m
network_operator_container  | /app/AEYE_Network_Operator/settings.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 07, 2024 - 08:17:30
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:17:33 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:17:33 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:17:33 [ NetOper API ANO ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mMW - Inference received message : Request AI Inference [39m
network_operator_container  | -----------------------------------------
network_operator_container  | [07/Aug/2024 08:17:33] [m"POST /mw/ai-inference/ HTTP/1.1" 200 34[0m
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:17:33 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received data from : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | [07/Aug/2024 08:17:33] [m"POST /api/ai-network-operator/ HTTP/1.1" 200 46[0m
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:17:44 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:17:44 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:17:44 [ NetOper API ANO ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mMW - Inference received message : Request AI Inference [39m
network_operator_container  | -----------------------------------------
network_operator_container  | [07/Aug/2024 08:17:44] [m"POST /mw/ai-inference/ HTTP/1.1" 200 34[0m
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:17:44 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received data from : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | [07/Aug/2024 08:17:44] [m"POST /api/ai-network-operator/ HTTP/1.1" 200 46[0m
network_operator_container  | /app/AEYE_Network_Operator/settings.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 07, 2024 - 08:18:27
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:18:30 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:18:30 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:18:30 [ NetOper API ANO ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mMW - Inference received message : Request AI Inference [39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:18:30 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received data from : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------[07/Aug/2024 08:18:30] [m"POST /mw/ai-inference/ HTTP/1.1" 200 34[0m
network_operator_container  | 
network_operator_container  | [07/Aug/2024 08:18:30] [m"POST /api/ai-network-operator/ HTTP/1.1" 200 46[0m
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 07, 2024 - 08:23:36
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:23:42 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:23:42 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:23:42 [ NetOper API ANO ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mMW - Inference received message : Request AI Inference [39m
network_operator_container  | -----------------------------------------
network_operator_container  | Internal Server Error: /mw/ai-inference/
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
network_operator_container  |     response = get_response(request)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
network_operator_container  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
network_operator_container  |     return view_func(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
network_operator_container  |     return self.dispatch(request, *args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
network_operator_container  |     response = self.handle_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
network_operator_container  |     self.raise_uncaught_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
network_operator_container  |     raise exc
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
network_operator_container  |     response = handler(request, *args, **kwargs)
network_operator_container  |   File "/app/mw/views/AEYE_Inference.py", line 57, in create
network_operator_container  |     img_file_path = os.path.join(os.path.dirname(__file__), 'images', image.filename)
network_operator_container  | AttributeError: 'InMemoryUploadedFile' object has no attribute 'filename'
network_operator_container  | [07/Aug/2024 08:23:42] [35;1m"POST /mw/ai-inference/ HTTP/1.1" 500 85382[0m
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:23:42 [ NetOper API ANO ] send to : [34m[ NetOper API - ANO ][39m
network_operator_container  | [31m[error] [31mfailed to send data to : http://127.0.0.1:3000/mw/ai-inference/
network_operator_container  |         received message from the server: Failed to Receive Data [NetOper - ANO][39m
network_operator_container  | -----------------------------------------
network_operator_container  | Bad Request: /api/ai-network-operator/
network_operator_container  | [07/Aug/2024 08:23:42] [31;1m"POST /api/ai-network-operator/ HTTP/1.1" 400 76[0m
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 07, 2024 - 08:23:47
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 07, 2024 - 08:24:23
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:24:25 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:24:25 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:24:25 [ NetOper API ANO ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mMW - Inference received message : Request AI Inference [39m
network_operator_container  | -----------------------------------------
network_operator_container  | /app/mw/views/images/CNV-1569-1.jpeg
network_operator_container  | [07/Aug/2024 08:24:25] [m"POST /mw/ai-inference/ HTTP/1.1" 200 34[0m
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 08:24:25 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received data from : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | [07/Aug/2024 08:24:25] [m"POST /api/ai-network-operator/ HTTP/1.1" 200 46[0m
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | Exception in thread django-main-thread:
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
network_operator_container  |     self.run()
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
network_operator_container  |     self._target(*self._args, **self._kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
network_operator_container  |     fn(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
network_operator_container  |     self.check(display_num_errors=True)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
network_operator_container  |     all_issues = checks.run_checks(
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
network_operator_container  |     new_errors = check(app_configs=app_configs, databases=databases)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
network_operator_container  |     return check_resolver(resolver)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
network_operator_container  |     return check_method()
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
network_operator_container  |     for pattern in self.url_patterns:
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
network_operator_container  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
network_operator_container  |     return import_module(self.urlconf_name)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/AEYE_Network_Operator/urls.py", line 23, in <module>
network_operator_container  |     path('mw/',  include('mw.urls')),
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
network_operator_container  |     urlconf_module = import_module(urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/mw/urls.py", line 5, in <module>
network_operator_container  |     from .views.AEYE_Inference import aeye_inference_Viewswets
network_operator_container  |   File "/app/mw/views/AEYE_Inference.py", line 169
network_operator_container  |     response_image  = aeye_upload_image_in_chunks(file_path=img_file_path, chunk_size=)
network_operator_container  |                                                                                       ^
network_operator_container  | SyntaxError: invalid syntax
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 07, 2024 - 08:26:09
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 07, 2024 - 09:04:56
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
