time="2024-08-09T18:13:53+09:00" level=warning msg="/home/yoonchcul/Documents/Hanium_2024/AEYE_AI/develop/AEYE_AI/Docker/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
time="2024-08-09T18:13:53+09:00" level=warning msg="Found orphan containers ([seminar_container]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
 Container opticnet_container  Created
 Container network_operator_container  Running
Attaching to network_operator_container, opticnet_container
opticnet_container          |  * Serving Flask app "AEYE" (lazy loading)
opticnet_container          |  * Environment: production
opticnet_container          |    WARNING: This is a development server. Do not use it in a production deployment.
opticnet_container          |    Use a production WSGI server instead.
opticnet_container          |  * Debug mode: on
opticnet_container          | Using TensorFlow backend.
opticnet_container          | INFO:werkzeug: * Running on http://0.0.0.0:2000/ (Press CTRL+C to quit)
opticnet_container          | INFO:werkzeug: * Restarting with stat
opticnet_container          | Using TensorFlow backend.
opticnet_container          | WARNING:werkzeug: * Debugger is active!
opticnet_container          | INFO:werkzeug: * Debugger PIN: 277-641-513
opticnet_container          | INFO:werkzeug: * Detected change in '/app/AEYE_AI/AEYE_HAL/AEYE_Inference.py', reloading
opticnet_container          | INFO:werkzeug: * Restarting with stat
opticnet_container          | Using TensorFlow backend.
opticnet_container          | WARNING:werkzeug: * Debugger is active!
opticnet_container          | INFO:werkzeug: * Debugger PIN: 277-641-513
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:14:34
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:14:51
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:15:04
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:15:07
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | Exception in thread django-main-thread:
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
network_operator_container  |     self.run()
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
network_operator_container  |     self._target(*self._args, **self._kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
network_operator_container  |     fn(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
network_operator_container  |     self.check(display_num_errors=True)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
network_operator_container  |     all_issues = checks.run_checks(
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
network_operator_container  |     new_errors = check(app_configs=app_configs, databases=databases)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
network_operator_container  |     return check_resolver(resolver)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
network_operator_container  |     return check_method()
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
network_operator_container  |     for pattern in self.url_patterns:
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
network_operator_container  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
network_operator_container  |     return import_module(self.urlconf_name)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/AEYE_Network_Operator/urls.py", line 22, in <module>
network_operator_container  |     path('api/', include('api.urls')),
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
network_operator_container  |     urlconf_module = import_module(urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/api/urls.py", line 5, in <module>
network_operator_container  |     from .views.AEYE_ANO import aeye_ano_Viewsets
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 53
network_operator_container  |     response = aeye_ai_inference_request(image, url)
network_operator_container  |     ^
network_operator_container  | IndentationError: unexpected indent
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:15:28
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:15:32
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:15:35
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:15:36
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:15:38
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:15:42 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:15:42 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | Internal Server Error: /api/ai-network-operator/
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
network_operator_container  |     response = get_response(request)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
network_operator_container  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
network_operator_container  |     return view_func(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
network_operator_container  |     return self.dispatch(request, *args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
network_operator_container  |     response = self.handle_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
network_operator_container  |     self.raise_uncaught_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
network_operator_container  |     raise exc
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
network_operator_container  |     response = handler(request, *args, **kwargs)
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 51, in create
network_operator_container  |     respons = loop.run_until_complete(aeye_ai_inference_request(image, url))
network_operator_container  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
network_operator_container  |     return future.result()
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 88, in aeye_ai_inference_request
network_operator_container  |     async with session.post(url, data=data, files=files) as response:
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1160, in post
network_operator_container  |     self._request(hdrs.METH_POST, url, data=data, **kwargs)
network_operator_container  | TypeError: _request() got an unexpected keyword argument 'files'
network_operator_container  | [09/Aug/2024 09:15:42] [35;1m"POST /api/ai-network-operator/ HTTP/1.1" 500 109049[0m
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:16:20
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:16:31
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:17:45
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:24:20
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:25:20
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
opticnet_container          | INFO:werkzeug: * Detected change in '/app/AEYE_AI/AEYE_APPLICATION/AEYE_AOT.py', reloading
opticnet_container          | INFO:werkzeug: * Restarting with stat
opticnet_container          | Using TensorFlow backend.
opticnet_container          | WARNING:werkzeug: * Debugger is active!
opticnet_container          | INFO:werkzeug: * Debugger PIN: 277-641-513
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:28:31
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:28:35
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:28:36
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:28:42
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:28:47
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:28:49
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:28:50
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:29:00
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | Exception in thread django-main-thread:
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
network_operator_container  |     self.run()
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
network_operator_container  |     self._target(*self._args, **self._kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
network_operator_container  |     fn(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
network_operator_container  |     self.check(display_num_errors=True)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
network_operator_container  |     all_issues = checks.run_checks(
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
network_operator_container  |     new_errors = check(app_configs=app_configs, databases=databases)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
network_operator_container  |     return check_resolver(resolver)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
network_operator_container  |     return check_method()
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
network_operator_container  |     for pattern in self.url_patterns:
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
network_operator_container  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
network_operator_container  |     return import_module(self.urlconf_name)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/AEYE_Network_Operator/urls.py", line 22, in <module>
network_operator_container  |     path('api/', include('api.urls')),
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
network_operator_container  |     urlconf_module = import_module(urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/api/urls.py", line 5, in <module>
network_operator_container  |     from .views.AEYE_ANO import aeye_ano_Viewsets
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 98
network_operator_container  |     print_log('error', whoami, i_am_api_ano, ) )
network_operator_container  |     ^
network_operator_container  | SyntaxError: invalid syntax
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | Exception in thread django-main-thread:
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
network_operator_container  |     self.run()
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
network_operator_container  |     self._target(*self._args, **self._kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
network_operator_container  |     fn(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
network_operator_container  |     self.check(display_num_errors=True)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
network_operator_container  |     all_issues = checks.run_checks(
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
network_operator_container  |     new_errors = check(app_configs=app_configs, databases=databases)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
network_operator_container  |     return check_resolver(resolver)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
network_operator_container  |     return check_method()
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
network_operator_container  |     for pattern in self.url_patterns:
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
network_operator_container  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
network_operator_container  |     return import_module(self.urlconf_name)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/AEYE_Network_Operator/urls.py", line 22, in <module>
network_operator_container  |     path('api/', include('api.urls')),
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
network_operator_container  |     urlconf_module = import_module(urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/api/urls.py", line 5, in <module>
network_operator_container  |     from .views.AEYE_ANO import aeye_ano_Viewsets
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 98
network_operator_container  |     print_log('error', whoami, i_am_api_ano, message) )
network_operator_container  |     ^
network_operator_container  | SyntaxError: invalid syntax
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | Exception in thread django-main-thread:
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
network_operator_container  |     self.run()
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
network_operator_container  |     self._target(*self._args, **self._kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
network_operator_container  |     fn(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
network_operator_container  |     self.check(display_num_errors=True)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
network_operator_container  |     all_issues = checks.run_checks(
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
network_operator_container  |     new_errors = check(app_configs=app_configs, databases=databases)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
network_operator_container  |     return check_resolver(resolver)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
network_operator_container  |     return check_method()
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
network_operator_container  |     for pattern in self.url_patterns:
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
network_operator_container  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
network_operator_container  |     return import_module(self.urlconf_name)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/AEYE_Network_Operator/urls.py", line 22, in <module>
network_operator_container  |     path('api/', include('api.urls')),
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
network_operator_container  |     urlconf_module = import_module(urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/api/urls.py", line 5, in <module>
network_operator_container  |     from .views.AEYE_ANO import aeye_ano_Viewsets
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 98
network_operator_container  |     print_log('error', whoami, i_am_api_ano, message) )
network_operator_container  |     ^
network_operator_container  | SyntaxError: invalid syntax
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | Exception in thread django-main-thread:
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
network_operator_container  |     self.run()
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
network_operator_container  |     self._target(*self._args, **self._kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
network_operator_container  |     fn(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
network_operator_container  |     self.check(display_num_errors=True)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
network_operator_container  |     all_issues = checks.run_checks(
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
network_operator_container  |     new_errors = check(app_configs=app_configs, databases=databases)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
network_operator_container  |     return check_resolver(resolver)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
network_operator_container  |     return check_method()
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
network_operator_container  |     for pattern in self.url_patterns:
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
network_operator_container  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
network_operator_container  |     return import_module(self.urlconf_name)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/AEYE_Network_Operator/urls.py", line 22, in <module>
network_operator_container  |     path('api/', include('api.urls')),
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
network_operator_container  |     urlconf_module = import_module(urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/api/urls.py", line 5, in <module>
network_operator_container  |     from .views.AEYE_ANO import aeye_ano_Viewsets
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 98
network_operator_container  |     print_log('error', whoami, i_am_api_ano, message) )
network_operator_container  |                                                       ^
network_operator_container  | SyntaxError: unmatched ')'
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:29:29
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:29:31
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:29:42
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | Not Found: /
network_operator_container  | [09/Aug/2024 09:29:44] [33m"GET / HTTP/1.1" 404 2270[0m
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | Exception in thread django-main-thread:
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
network_operator_container  |     self.run()
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
network_operator_container  |     self._target(*self._args, **self._kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
network_operator_container  |     fn(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
network_operator_container  |     self.check(display_num_errors=True)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
network_operator_container  |     all_issues = checks.run_checks(
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
network_operator_container  |     new_errors = check(app_configs=app_configs, databases=databases)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
network_operator_container  |     return check_resolver(resolver)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
network_operator_container  |     return check_method()
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
network_operator_container  |     for pattern in self.url_patterns:
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
network_operator_container  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
network_operator_container  |     return import_module(self.urlconf_name)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/AEYE_Network_Operator/urls.py", line 22, in <module>
network_operator_container  |     path('api/', include('api.urls')),
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
network_operator_container  |     urlconf_module = import_module(urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/api/urls.py", line 5, in <module>
network_operator_container  |     from .views.AEYE_ANO import aeye_ano_Viewsets
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 98
network_operator_container  |     message="failed to send data to : {}\n" +\
network_operator_container  |                       received message from the server: {}".formaturl, message
network_operator_container  |                            ^
network_operator_container  | SyntaxError: invalid syntax
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:30:19
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:30:23
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:30:28
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:30:35
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:30:58
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:32:59
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:33:11
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:33:17
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:33:49
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:34:06
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:35:03
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | Exception in thread django-main-thread:
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
network_operator_container  |     self.run()
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
network_operator_container  |     self._target(*self._args, **self._kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
network_operator_container  |     fn(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
network_operator_container  |     self.check(display_num_errors=True)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
network_operator_container  |     all_issues = checks.run_checks(
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
network_operator_container  |     new_errors = check(app_configs=app_configs, databases=databases)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
network_operator_container  |     return check_resolver(resolver)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
network_operator_container  |     return check_method()
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
network_operator_container  |     for pattern in self.url_patterns:
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
network_operator_container  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
network_operator_container  |     return import_module(self.urlconf_name)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/AEYE_Network_Operator/urls.py", line 22, in <module>
network_operator_container  |     path('api/', include('api.urls')),
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
network_operator_container  |     urlconf_module = import_module(urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/api/urls.py", line 5, in <module>
network_operator_container  |     from .views.AEYE_ANO import aeye_ano_Viewsets
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 90
network_operator_container  |     async with session.post(url, data=data, files=files) as response:
network_operator_container  |                                                                     ^
network_operator_container  | IndentationError: unindent does not match any outer indentation level
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | Exception in thread django-main-thread:
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
network_operator_container  |     self.run()
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
network_operator_container  |     self._target(*self._args, **self._kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
network_operator_container  |     fn(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
network_operator_container  |     self.check(display_num_errors=True)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
network_operator_container  |     all_issues = checks.run_checks(
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
network_operator_container  |     new_errors = check(app_configs=app_configs, databases=databases)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
network_operator_container  |     return check_resolver(resolver)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
network_operator_container  |     return check_method()
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
network_operator_container  |     for pattern in self.url_patterns:
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
network_operator_container  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
network_operator_container  |     return import_module(self.urlconf_name)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/AEYE_Network_Operator/urls.py", line 22, in <module>
network_operator_container  |     path('api/', include('api.urls')),
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
network_operator_container  |     urlconf_module = import_module(urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/api/urls.py", line 5, in <module>
network_operator_container  |     from .views.AEYE_ANO import aeye_ano_Viewsets
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 90
network_operator_container  |     async with session.post(url, data=data, files=files) as response:
network_operator_container  |     ^
network_operator_container  | IndentationError: unexpected indent
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:35:12
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:35:18
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:35:24
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:35:36
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:35:41
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:35:54
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:36:11
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:36:16
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | Exception in thread django-main-thread:
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
network_operator_container  |     self.run()
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
network_operator_container  |     self._target(*self._args, **self._kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
network_operator_container  |     fn(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
network_operator_container  |     self.check(display_num_errors=True)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
network_operator_container  |     all_issues = checks.run_checks(
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
network_operator_container  |     new_errors = check(app_configs=app_configs, databases=databases)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
network_operator_container  |     return check_resolver(resolver)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
network_operator_container  |     return check_method()
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
network_operator_container  |     for pattern in self.url_patterns:
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
network_operator_container  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
network_operator_container  |     return import_module(self.urlconf_name)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/AEYE_Network_Operator/urls.py", line 22, in <module>
network_operator_container  |     path('api/', include('api.urls')),
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
network_operator_container  |     urlconf_module = import_module(urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/api/urls.py", line 5, in <module>
network_operator_container  |     from .views.AEYE_ANO import aeye_ano_Viewsets
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 89
network_operator_container  |     form_data.add_field('image', image, filename=image.name, content_type=image.content_type)
network_operator_container  |     ^
network_operator_container  | IndentationError: unexpected indent
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:36:20
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:36:31
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:36:40
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:36:43
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:36:45
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:36:50
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:36:54
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:37:38
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:37:41
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:38:16
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | Exception in thread django-main-thread:
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
network_operator_container  |     self.run()
network_operator_container  |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
network_operator_container  |     self._target(*self._args, **self._kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
network_operator_container  |     fn(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
network_operator_container  |     self.check(display_num_errors=True)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
network_operator_container  |     all_issues = checks.run_checks(
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
network_operator_container  |     new_errors = check(app_configs=app_configs, databases=databases)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
network_operator_container  |     return check_resolver(resolver)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
network_operator_container  |     return check_method()
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
network_operator_container  |     for pattern in self.url_patterns:
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
network_operator_container  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
network_operator_container  |     res = instance.__dict__[self.name] = self.func(instance)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
network_operator_container  |     return import_module(self.urlconf_name)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/AEYE_Network_Operator/urls.py", line 22, in <module>
network_operator_container  |     path('api/', include('api.urls')),
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
network_operator_container  |     urlconf_module = import_module(urlconf_module)
network_operator_container  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
network_operator_container  |     return _bootstrap._gcd_import(name[level:], package, level)
network_operator_container  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
network_operator_container  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
network_operator_container  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
network_operator_container  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
network_operator_container  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
network_operator_container  |   File "/app/api/urls.py", line 5, in <module>
network_operator_container  |     from .views.AEYE_ANO import aeye_ano_Viewsets
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 92
network_operator_container  |     print_log('active', whoami, i_am_api_ano, "received data from : {}".format(url))
network_operator_container  |     ^
network_operator_container  | IndentationError: unexpected indent
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:38:20
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:38:53
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:38:55
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:38:57
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:38:59
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:39:17
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:39:32 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:39:32 [ NetOper API - ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | Internal Server Error: /api/ai-network-operator/
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
network_operator_container  |     response = get_response(request)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
network_operator_container  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
network_operator_container  |     return view_func(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
network_operator_container  |     return self.dispatch(request, *args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
network_operator_container  |     response = self.handle_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
network_operator_container  |     self.raise_uncaught_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
network_operator_container  |     raise exc
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
network_operator_container  |     response = handler(request, *args, **kwargs)
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 51, in create
network_operator_container  |     response = loop.run_until_complete(aeye_ai_inference_request(image, url))
network_operator_container  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
network_operator_container  |     return future.result()
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 83, in aeye_ai_inference_request
network_operator_container  |     form_data.add_field('message', message)
network_operator_container  | UnboundLocalError: local variable 'message' referenced before assignment
network_operator_container  | [09/Aug/2024 09:39:32] [35;1m"POST /api/ai-network-operator/ HTTP/1.1" 500 94404[0m
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:40:13
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:40:20
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:40:26 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:40:26 [ NetOper API - ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | Internal Server Error: /api/ai-network-operator/
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/aiohttp/formdata.py", line 148, in _gen_form_data
network_operator_container  |     part = payload.get_payload(
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/aiohttp/payload.py", line 71, in get_payload
network_operator_container  |     return PAYLOAD_REGISTRY.get(data, *args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/aiohttp/payload.py", line 118, in get
network_operator_container  |     raise LookupError()
network_operator_container  | aiohttp.payload.LookupError
network_operator_container  | 
network_operator_container  | The above exception was the direct cause of the following exception:
network_operator_container  | 
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
network_operator_container  |     response = get_response(request)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
network_operator_container  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
network_operator_container  |     return view_func(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
network_operator_container  |     return self.dispatch(request, *args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
network_operator_container  |     response = self.handle_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
network_operator_container  |     self.raise_uncaught_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
network_operator_container  |     raise exc
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
network_operator_container  |     response = handler(request, *args, **kwargs)
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 51, in create
network_operator_container  |     response = loop.run_until_complete(aeye_ai_inference_request(image, url))
network_operator_container  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
network_operator_container  |     return future.result()
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 86, in aeye_ai_inference_request
network_operator_container  |     async with session.post(url, data=form_data) as response:
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1353, in __aenter__
network_operator_container  |     self._resp = await self._coro
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 625, in _request
network_operator_container  |     req = self._request_class(
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 336, in __init__
network_operator_container  |     self.update_body_from_data(data)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 554, in update_body_from_data
network_operator_container  |     body = body()
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/aiohttp/formdata.py", line 180, in __call__
network_operator_container  |     return self._gen_form_data()
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/aiohttp/formdata.py", line 159, in _gen_form_data
network_operator_container  |     raise TypeError(
network_operator_container  | TypeError: Can not serialize value type: <class 'django.core.files.uploadedfile.InMemoryUploadedFile'>
network_operator_container  |  headers: {'Content-Type': 'image/jpeg'}
network_operator_container  |  value: <InMemoryUploadedFile: CNV-1569-1.jpeg (image/jpeg)>
network_operator_container  | [09/Aug/2024 09:40:26] [35;1m"POST /api/ai-network-operator/ HTTP/1.1" 500 144129[0m
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:42:43
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:42:45 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:42:45 [ NetOper API - ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:42:45 [ MW - Inference] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [31m[error] [31mFailed to Received Data : <QueryDict: {'whoami': ['NetOper API - ANO'], 'message': ['Request to AI Inference'], 'image': [<InMemoryUploadedFile: CNV-1569-1.jpeg (image/jpeg)>]}> [39m
network_operator_container  | -----------------------------------------
network_operator_container  | Bad Request: /mw/ai-inference/
network_operator_container  | [09/Aug/2024 09:42:45] [31;1m"POST /mw/ai-inference/ HTTP/1.1" 400 75[0m
network_operator_container  | Internal Server Error: /api/ai-network-operator/
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
network_operator_container  |     response = get_response(request)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
network_operator_container  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
network_operator_container  |     return view_func(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
network_operator_container  |     return self.dispatch(request, *args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
network_operator_container  |     response = self.handle_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
network_operator_container  |     self.raise_uncaught_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
network_operator_container  |     raise exc
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
network_operator_container  |     response = handler(request, *args, **kwargs)
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 51, in create
network_operator_container  |     response = loop.run_until_complete(aeye_ai_inference_request(image, url))
network_operator_container  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
network_operator_container  |     return future.result()
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 87, in aeye_ai_inference_request
network_operator_container  |     result = await response
network_operator_container  | TypeError: object ClientResponse can't be used in 'await' expression
network_operator_container  | [09/Aug/2024 09:42:45] [35;1m"POST /api/ai-network-operator/ HTTP/1.1" 500 95423[0m
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:45:31
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:45:33
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:45:36
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:50:51
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:50:57
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | /app/mw/views/AEYE_Inference.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:50:59
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:51:04 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:51:04 [ NetOper API - ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:51:04 [ MW - Inference] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [31m[error] [31mReceived Invalid Data : {'message': [ErrorDetail(string='Ensure this field has no more than 20 characters.', code='max_length')]} [39m
network_operator_container  | -----------------------------------------
network_operator_container  | Bad Request: /mw/ai-inference/
network_operator_container  | [09/Aug/2024 09:51:04] [31;1m"POST /mw/ai-inference/ HTTP/1.1" 400 75[0m
network_operator_container  | [09/Aug/2024 09:51:04,032] - Broken pipe from ('127.0.0.1', 38562)
network_operator_container  | 
network_operator_container  | Internal Server Error: /api/ai-network-operator/
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
network_operator_container  |     response = get_response(request)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
network_operator_container  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
network_operator_container  |     return view_func(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
network_operator_container  |     return self.dispatch(request, *args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
network_operator_container  |     response = self.handle_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
network_operator_container  |     self.raise_uncaught_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
network_operator_container  |     raise exc
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
network_operator_container  |     response = handler(request, *args, **kwargs)
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 51, in create
network_operator_container  |     response = loop.run_until_complete(aeye_ai_inference_request(image, url))
network_operator_container  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
network_operator_container  |     return future.result()
network_operator_container  |   File "/app/api/views/AEYE_ANO.py", line 87, in aeye_ai_inference_request
network_operator_container  |     result = await response
network_operator_container  | TypeError: object ClientResponse can't be used in 'await' expression
network_operator_container  | [09/Aug/2024 09:51:04] [35;1m"POST /api/ai-network-operator/ HTTP/1.1" 500 95423[0m
network_operator_container  | /app/api/views/AEYE_ANO.py changed, reloading.
network_operator_container  | [0mWatching for file changes with StatReloader
network_operator_container  | Performing system checks...
network_operator_container  | 
network_operator_container  | System check identified no issues (0 silenced).
network_operator_container  | August 09, 2024 - 09:51:25
network_operator_container  | Django version 3.2, using settings 'AEYE_Network_Operator.settings'
network_operator_container  | Starting development server at http://0.0.0.0:3000/
network_operator_container  | Quit the server with CONTROL-C.
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:51:30 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:51:30 [ NetOper API - ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:51:30 [ NetOper API - ANO ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mMW - Inference received message : Request AI Inference [39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:51:30 [ NetOper MW Inference ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mcheck server status : http://opticnet_container:2000/api/start-upload-file/ [39m
network_operator_container  | -----------------------------------------
opticnet_container          | INFO:root:
opticnet_container          | -----------------------------------------
opticnet_container          | 2024-08-09 09:51:30 [ NetOper MW Inference ] send to: [34m[ OpticNet - API UCTC ]
opticnet_container          | [39m[32m[OpticNet - active] [39mmessage: [ [32mNetOper MW Inference received valid from OpticNet - API UCTC ][39m
opticnet_container          | -----------------------------------------
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:30] "[37mPOST /api/start-upload-file/ HTTP/1.1[0m" 200 -
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:51:30 [ NetOper MW Inference ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mserver is ok : http://opticnet_container:2000/api/start-upload-file/ [39m
network_operator_container  | -----------------------------------------
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:30] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:30] "[37mPOST /api/data-assemble/ HTTP/1.1[0m" 200 -
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:51:30 [ NetOper MW Inference ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mcheck server status : http://opticnet_container:2000/api/start-upload-file/ [39m
network_operator_container  | -----------------------------------------
opticnet_container          | INFO:root:
opticnet_container          | -----------------------------------------
opticnet_container          | 2024-08-09 09:51:30 [ NetOper MW Inference ] send to: [34m[ OpticNet - API UCTC ]
opticnet_container          | [39m[32m[OpticNet - active] [39mmessage: [ [32mNetOper MW Inference received valid from OpticNet - API UCTC ][39m
opticnet_container          | -----------------------------------------
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:30] "[37mPOST /api/start-upload-file/ HTTP/1.1[0m" 200 -
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:51:30 [ NetOper MW Inference ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mserver is ok : http://opticnet_container:2000/api/start-upload-file/ [39m
network_operator_container  | -----------------------------------------
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:30] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:30] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:30] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:30] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:31] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:31] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:31] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:31] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:31] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:31] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:31] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:31] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:31] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:31] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:31] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:32] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:32] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:32] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:32] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:32] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:32] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:32] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:32] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:32] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:32] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:32] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:32] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:33] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:33] "[37mPOST /api/upload-file-chunk/ HTTP/1.1[0m" 200 -
opticnet_container          | INFO:werkzeug:172.18.0.2 - - [09/Aug/2024 09:51:33] "[37mPOST /api/data-assemble/ HTTP/1.1[0m" 200 -
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-09 09:51:33 [ NetOper MW Inference ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mrequest AI Inference to : http://opticnet_container:2000/api/ai-toolkit/ [39m
network_operator_container  | -----------------------------------------
opticnet_container          | INFO:root:
opticnet_container          | -----------------------------------------
opticnet_container          | 2024-08-09 09:51:33 [ NetOper MW Inference ] send to: [34m[ AEYE OpticNet AOT Inference ]
opticnet_container          | [39m[32m[active] [39mmessage: [ [32mClient Requested AEYE AOT ][39m
opticnet_container          | -----------------------------------------
opticnet_container          | INFO:root:
opticnet_container          | -----------------------------------------
opticnet_container          | 2024-08-09 09:51:33 [ AEYE OpticNet AOT Inference ] send to: [34m[ OpticNet HAL - Inference ]
opticnet_container          | [39m[32m[OpticNet - active] [39mmessage: [ [32mInitiate AI Inference ][39m
opticnet_container          | -----------------------------------------
opticnet_container          | INFO:root:
opticnet_container          | -----------------------------------------
opticnet_container          | 2024-08-09 09:51:33 [ AI Inference ] send to: [34m[ OpticNet MW - Status ]
opticnet_container          | [39m[32m[active] [39mmessage: [ [32mprocesssed_img: [[[[1.         1.         1.        ]
opticnet_container          |    [1.         1.         1.        ]
opticnet_container          |    [1.         1.         1.        ]
opticnet_container          |    ...
opticnet_container          |    [1.         1.         1.        ]
opticnet_container          |    [1.         1.         1.        ]
opticnet_container          |    [1.         1.         1.        ]]
opticnet_container          | 
opticnet_container          |   [[1.         1.         1.        ]
opticnet_container          |    [1.         1.         1.        ]
opticnet_container          |    [1.         1.         1.        ]
opticnet_container          |    ...
opticnet_container          |    [1.         1.         1.        ]
opticnet_container          |    [1.         1.         1.        ]
opticnet_container          |    [1.         1.         1.        ]]
opticnet_container          | 
opticnet_container          |   [[1.         1.         1.        ]
opticnet_container          |    [1.         1.         1.        ]
opticnet_container          |    [1.         1.         1.        ]
opticnet_container          |    ...
opticnet_container          |    [1.         1.         1.        ]
opticnet_container          |    [1.         1.         1.        ]
opticnet_container          |    [1.         1.         1.        ]]
opticnet_container          | 
opticnet_container          |   ...
opticnet_container          | 
opticnet_container          |   [[0.0745098  0.0745098  0.0745098 ]
opticnet_container          |    [0.00784314 0.00784314 0.00784314]
opticnet_container          |    [0.0627451  0.0627451  0.0627451 ]
opticnet_container          |    ...
opticnet_container          |    [0.         0.         0.        ]
opticnet_container          |    [0.         0.         0.        ]
opticnet_container          |    [0.         0.         0.        ]]
opticnet_container          | 
opticnet_container          |   [[0.01960784 0.01960784 0.01960784]
opticnet_container          |    [0.07843137 0.07843137 0.07843137]
opticnet_container          |    [0.04313725 0.04313725 0.04313725]
opticnet_container          |    ...
opticnet_container          |    [0.         0.         0.        ]
opticnet_container          |    [0.         0.         0.        ]
opticnet_container          |    [0.         0.         0.        ]]
opticnet_container          | 
opticnet_container          |   [[0.0627451  0.0627451  0.0627451 ]
opticnet_container          |    [0.04313725 0.04313725 0.04313725]
opticnet_container          |    [0.00392157 0.00392157 0.00392157]
opticnet_container          |    ...
opticnet_container          |    [0.         0.         0.        ]
opticnet_container          |    [0.         0.         0.        ]
opticnet_container          |    [0.         0.         0.        ]]]] ][39m
opticnet_container          | -----------------------------------------
opticnet_container          | INFO:werkzeug:127.0.0.1 - - [09/Aug/2024 09:51:33] "[37mPOST /mw/status HTTP/1.1[0m" 200 -
opticnet_container          | 2024-08-09 09:51:33.653533: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
opticnet_container          | 2024-08-09 09:51:33.721738: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
opticnet_container          | 2024-08-09 09:51:33.721907: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
opticnet_container          | name: NVIDIA GeForce RTX 3060 Laptop GPU major: 8 minor: 6 memoryClockRate(GHz): 1.425
opticnet_container          | pciBusID: 0000:01:00.0
opticnet_container          | totalMemory: 5.78GiB freeMemory: 5.10GiB
opticnet_container          | 2024-08-09 09:51:33.721922: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
opticnet_container          | 2024-08-09 09:51:34.237153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
opticnet_container          | 2024-08-09 09:51:34.237178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
opticnet_container          | 2024-08-09 09:51:34.237184: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
opticnet_container          | 2024-08-09 09:51:34.237263: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4844 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6)
