time="2024-08-07T21:21:22+09:00" level=warning msg="/home/yoonchcul/Documents/Hanium_2024/AEYE_AI/develop/Docker/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
time="2024-08-07T21:21:22+09:00" level=warning msg="Found orphan containers ([seminar_container]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
 Container opticnet_container  Running
 Container network_operator_container  Running
Attaching to network_operator_container, opticnet_container
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 12:21:29 [ Yoonchul ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] received message  : Request AI Inference
network_operator_container  |          received operation: Inference[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 12:21:29 [ NetOper API ANO ] send to : [94m[ NetOper API - ANO ][39m
network_operator_container  | [32m[active] send data to : http://127.0.0.1:3000/mw/ai-inference/[39m
network_operator_container  | -----------------------------------------
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 12:21:29 [ NetOper API ANO ] Send to : [94m[ NetOper MW - Inference ][39m
network_operator_container  | [32m[active] [32mMW - Inference received message : Request AI Inference [39m
network_operator_container  | -----------------------------------------
network_operator_container  | Internal Server Error: /mw/ai-inference/
network_operator_container  | Traceback (most recent call last):
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
network_operator_container  |     response = get_response(request)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
network_operator_container  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
network_operator_container  |     return view_func(*args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
network_operator_container  |     return self.dispatch(request, *args, **kwargs)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
network_operator_container  |     response = self.handle_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
network_operator_container  |     self.raise_uncaught_exception(exc)
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
network_operator_container  |     raise exc
network_operator_container  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
network_operator_container  |     response = handler(request, *args, **kwargs)
network_operator_container  |   File "/app/mw/views/AEYE_Inference.py", line 56, in create
network_operator_container  |     response = aeye_ai_inference_request(image)
network_operator_container  |   File "/app/mw/views/AEYE_Inference.py", line 169, in aeye_ai_inference_request
network_operator_container  |     response_image  = aeye_upload_image_in_chunks(file_path=img_file_path, chunk_size=chunk_size)
network_operator_container  |   File "/app/mw/views/AEYE_Inference.py", line 91, in aeye_upload_image_in_chunks
network_operator_container  |     print_log('active', whoami, mw, message)
network_operator_container  |   File "/app/mw/views/AEYE_Inference.py", line 20, in print_log
network_operator_container  |     print("\n-----------------------------------------\n"   +
network_operator_container  | TypeError: can only concatenate str (not "tuple") to str
network_operator_container  | [07/Aug/2024 12:21:30] [35;1m"POST /mw/ai-inference/ HTTP/1.1" 500 100238[0m
network_operator_container  | 
network_operator_container  | -----------------------------------------
network_operator_container  | 2024-08-07 12:21:30 [ NetOper API ANO ] send to : [34m[ NetOper API - ANO ][39m
network_operator_container  | [31m[error] [31mfailed to send data to : http://127.0.0.1:3000/mw/ai-inference/
network_operator_container  |         received message from the server: Failed to Receive Data [NetOper - ANO][39m
network_operator_container  | -----------------------------------------
network_operator_container  | Bad Request: /api/ai-network-operator/
network_operator_container  | [07/Aug/2024 12:21:30] [31;1m"POST /api/ai-network-operator/ HTTP/1.1" 400 76[0m
